import { useSession } from "next-auth/react";
import Head from "next/head";
import PodcastCard from "~/components/PodcastCard";
import { api } from "~/utils/api";

export default function Home() {
  const { data: sessionData } = useSession();
  const podcasts = api.podcast.getPodcast.useQuery({
    category: "history",
    languageCode: "en",
    limit: 10,
  });
  console.log(sessionData);
  return (
    <>
      <Head>
        <title>DropPod</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="shortcut icon" href="/images/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/images/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/images/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/images/favicon-16x16.png"
        />
      </Head>
      <main className=" overflow-auto ">
        {sessionData && (
          <div className="grid grid-cols-4  gap-4 overflow-x-hidden">
            {podcasts.data &&
              podcasts.data.map((p) => (
                <PodcastCard key={p.guid + "_card"} data={p} />
              ))}
          </div>
        )}
        {!sessionData && <p>NOT SIGNED IN</p>}
      </main>
    </>
  );
}
